## .eslintrc.yml
env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/vue3-essential
  - standard-with-typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  # - import
  - prettier
rules: {
  eqeqeq: off
  curly: error
  quotes:
    - error
    - double
}